<section class="section-cuaan">
    <div class="container-cuaminh">
        <div class="section_header">
            <h2 class="section_header_title">Latest Feature Jobs</h2>
            <a href="./jobs.php" class="section_header_link">See More &nbsp; &rarr;</a>
        </div>
        <div class="features">
        <div class="featured_card">
                <img src="images/anhnghe1.jpg" alt="" class="featured_img" />

                <div class="card_body">
                  <h3 class="featured_title">Database Engineer</h3>
                  <p class="featured_p">
                      A database engineer designs, implements, and manages database systems, optimizing performance, maintaining data integrity, and implementing security measures.
                       They ensure efficient data storage and retrieval, playing a crucial role in safeguarding sensitive information..</p> 

                  <div class="featured_icon_box">
                    <img src="images/clock.png" alt="" class="featured_icon" />
                    Full-Time
                  </div>

                  <div class="featured_icon_box">
                    <img src="images/location.png" alt="" class="featured_icon" />
                    Ha Noi
                  </div>

                  <form action="./jobs.php" method="get">
                    <button type="submit"  class="featured_btn">More Details</button>
                    </form>
                </div>
              </div>

              <div class="featured_card">
                <img src="images/anhnghe2.jpg" alt="" class="featured_img" />
                <div class="card_body">
                  <h3 class="featured_title">Full-Stack Developer</h3>
                  <p class="featured_p">
                    A software developer writes, tests, and maintains code for creating software applications. 
                    They collaborate with teams to design and implement solutions meeting specific user or business needs,
                     ensuring the development of functional and efficient software products.</p>
                  <div class="featured_icon_box">
                    <img src="images/clock.png" alt="" class="featured_icon" />
                    Full-Time
                  </div>
                  <div class="featured_icon_box">
                    <img src="images/location.png" alt="" class="featured_icon" />
                    Da Nang
                  </div>
                  <form action="./jobs.php" method="get">
                    <button type="submit"  class="featured_btn">More Details</button>
                    </form>
                </div>
              </div>

              <div class="featured_card">
                <img src="images/anhnghe3.jpeg" alt="" class="featured_img" />
                <div class="card_body">
                  <h3 class="featured_title">HR Director</h3>
                  <p class="featured_p">
                          The HR Director is a senior leader managing human resources strategies and policies,
                              aligning them with organizational goals and ensuring legal compliance.
                                  They focus on talent management, employee development
                                  and contribute to fostering a positive workplace culture.</p>
                  <div class="featured_icon_box">
                    <img src="images/clock.png" alt="" class="featured_icon" />
                    Full-Time
                  </div>
                  <div class="featured_icon_box">
                    <img src="images/location.png" alt="" class="featured_icon" />
                    Ho Chi Minh City
                  </div>
                  <form action="./jobs.php" method="get">
                  <button type="submit"  class="featured_btn">More Details</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</section>
