<header class="header-cuatuan">
    <div class="brand">
        <a href="index.php"><img class="logo" src="images/logo2.png" alt="companylogo"></a>
    </div>
    <nav>
        <ul class="menu">
            <li><a href="jobs.php">JOBS</a></li>
            <li><a href="apply.php">APPLY HERE</a></li>
            <li><a href="about.php">ABOUT</a></li>
            <li><a href="enhancements.php">ENHANCEMENTS</a></li>
            <li><a href="#">CONTACT US</a>
            <li><a href = "login.php">LOGIN</a></li>
                <ul class="dropdown">
                    <li><a href="mailto:">Doan Phuong Anh Tuan</a></li>
                    <li><a href="mailto:">Nguyen Hoang Minh</a></li>
                    <li><a href="mailto:">Le Gia Hoang An</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</header>